"""Deterministic MockAdapter for offline development, failure simulation, and zero-cost testing."""

import asyncio
import json
import time
from typing import Any, AsyncIterator, Dict, List, Optional
from app.adapters.base import BaseModelAdapter, GenerationRequest, GenerationResponse, ModelInfo, StreamChunk


class MockAdapterError(Exception):
    """Exception raised for simulated provider errors."""
    pass


class MockAdapter(BaseModelAdapter):
    """Deterministic, zero-dependency model adapter for offline operation and failure testing."""

    def __init__(self, model_name: str = "mock-deterministic", config: Optional[Dict[str, Any]] = None):
        super().__init__(model_name, config)

    def supports_structured_output(self) -> bool:
        return True

    def get_model_info(self) -> ModelInfo:
        return ModelInfo(
            name=self.model_name,
            provider="mock",
            supports_structured=True,
            supports_streaming=True,
            context_window=8192,
            input_price_per_1k=0.0,
            output_price_per_1k=0.0,
            is_mock=True,
            description="Deterministic offline mock adapter with controlled failure simulation modes."
        )

    def _determine_scenario(self, request: GenerationRequest) -> str:
        """Extract scenario trigger from metadata, variables, or prompt text."""
        if "mock_scenario" in request.metadata:
            return str(request.metadata["mock_scenario"]).upper()

        if "mock_scenario" in request.variables:
            return str(request.variables["mock_scenario"]).upper()

        # Check prompt for explicit scenario tags
        prompt_upper = request.prompt.upper()
        scenarios = [
            "MOCK_MALFORMED_JSON",
            "MOCK_MISSING_FIELD",
            "MOCK_WRONG_TYPE",
            "MOCK_TIMEOUT",
            "MOCK_INTERRUPTED_STREAM",
            "MOCK_PROVIDER_ERROR",
            "MOCK_VALID",
        ]
        for s in scenarios:
            if s in prompt_upper:
                return s

        return "MOCK_VALID"

    def _get_valid_payload_for_task(self, task_type: str, variables: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a deterministic, schema-compliant dictionary based on task type."""
        if task_type == "event_brief":
            # Extract names from variables if provided
            user_text = str(variables.get("instruction", "") or variables.get("input", ""))
            event_name = "Tech Innovation Summit 2026"
            location = "New Delhi, India"
            date = "2026-11-15"

            if "delhi" in user_text.lower():
                location = "Delhi, India"
            if "trip" in user_text.lower() or "tour" in user_text.lower():
                event_name = "Delhi Heritage & Food Tour"

            return {
                "event_name": event_name,
                "date": date,
                "location": location,
                "description": "Structured itinerary and logistical brief compiled from input constraints."
            }
        elif task_type == "content_pack":
            return {
                "headline": "PromptOps Revolutionizes Generative AI Reliability",
                "summary": "Engineering teams adopt strict validation and prompt registry pipelines.",
                "key_points": [
                    "Controlled generation over raw chatbots",
                    "Automated schema repair loops",
                    "Deterministic offline evaluation"
                ],
                "target_audience": "Software Engineers and AI Architects"
            }
        else:
            return {
                "status": "success",
                "task": task_type,
                "message": "Deterministic structured output generated by MockAdapter",
                "data": variables
            }

    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        start_time = time.perf_counter()
        scenario = self._determine_scenario(request)

        # Handle repair or fallback scenario: if prompt indicates repair or fallback recovery, return valid fixed JSON
        is_repair_attempt = (
            request.metadata.get("is_repair", False)
            or request.metadata.get("fallback_activated", False)
            or "REPAIR ATTEMPT" in request.prompt.upper()
            or "VALIDATION ERROR" in request.prompt.upper()
        )

        # 1. Timeout simulation
        if scenario == "MOCK_TIMEOUT" and not is_repair_attempt:
            # Simulate request timeout
            simulated_timeout = min(request.timeout or 1.0, 0.1)
            await asyncio.sleep(simulated_timeout)
            raise asyncio.TimeoutError(f"[MOCK] Simulated timeout occurred after {simulated_timeout}s")

        # 2. Provider error simulation
        if scenario == "MOCK_PROVIDER_ERROR" and not is_repair_attempt:
            raise MockAdapterError("[MOCK] Simulated HTTP 503: Model provider service temporarily unavailable")

        # Compute deterministic text
        if is_repair_attempt:
            # Repair successfully recovers to valid schema
            payload = self._get_valid_payload_for_task(request.task_type, request.variables)
            raw_text = json.dumps(payload, indent=2)
        elif scenario == "MOCK_MALFORMED_JSON":
            # Unterminated JSON string with markdown syntax
            raw_text = '```json\n{\n  "event_name": "Broken Event JSON",\n  "date": "2026-11-15",\n  "location": "Incomplete string'
        elif scenario == "MOCK_MISSING_FIELD":
            # Missing mandatory fields 'event_name' and 'description'
            raw_text = json.dumps({
                "date": "2026-11-15",
                "location": "New Delhi, India"
            }, indent=2)
        elif scenario == "MOCK_WRONG_TYPE":
            # Types violate schema (e.g. integer for string, array for date)
            raw_text = json.dumps({
                "event_name": 12345,
                "date": ["invalid", "date", "type"],
                "location": False,
                "description": 999.99
            }, indent=2)
        else:
            # MOCK_VALID
            payload = self._get_valid_payload_for_task(request.task_type, request.variables)
            raw_text = json.dumps(payload, indent=2)

        # Calculate metrics
        latency_ms = round((time.perf_counter() - start_time) * 1000.0, 2)
        input_tokens = max(1, len(request.prompt) // 4)
        output_tokens = max(1, len(raw_text) // 4)

        return GenerationResponse(
            text=raw_text,
            structured_output=None,  # Validation pipeline will parse and validate
            model=self.model_name,
            provider="mock",
            finish_reason="stop",
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            latency_ms=latency_ms,
            estimated_cost=0.0,
            cached=False,
            status="SUCCESS",
            raw_response=raw_text
        )

    async def stream(self, request: GenerationRequest) -> AsyncIterator[StreamChunk]:
        scenario = self._determine_scenario(request)
        is_repair_attempt = (
            request.metadata.get("is_repair", False)
            or request.metadata.get("fallback_activated", False)
            or "REPAIR ATTEMPT" in request.prompt.upper()
            or "VALIDATION ERROR" in request.prompt.upper()
        )

        if scenario == "MOCK_TIMEOUT" and not is_repair_attempt:
            await asyncio.sleep(0.05)
            raise asyncio.TimeoutError("[MOCK] Simulated timeout during streaming")

        if scenario == "MOCK_PROVIDER_ERROR" and not is_repair_attempt:
            raise MockAdapterError("[MOCK] Simulated provider failure before stream initiation")

        # Determine output text
        if is_repair_attempt or scenario == "MOCK_VALID":
            payload = self._get_valid_payload_for_task(request.task_type, request.variables)
            full_text = json.dumps(payload, indent=2)
        elif scenario == "MOCK_MALFORMED_JSON":
            full_text = '{\n  "event_name": "Broken Event",\n  "date": "2026-11-15'
        elif scenario == "MOCK_MISSING_FIELD":
            full_text = json.dumps({"date": "2026-11-15", "location": "New Delhi"}, indent=2)
        elif scenario == "MOCK_WRONG_TYPE":
            full_text = json.dumps({"event_name": 999, "date": False}, indent=2)
        else:
            full_text = json.dumps(self._get_valid_payload_for_task(request.task_type, request.variables), indent=2)

        # Break into chunks
        words = full_text.split(" ")
        for i, word in enumerate(words):
            if scenario == "MOCK_INTERRUPTED_STREAM" and not is_repair_attempt and i >= 3:
                raise MockAdapterError("[MOCK] Simulated stream connection reset / interruption")

            separator = " " if i < len(words) - 1 else ""
            yield StreamChunk(
                text=word + separator,
                finish_reason="stop" if i == len(words) - 1 else None
            )
            await asyncio.sleep(0.005)  # Micro-delay to simulate streaming arrival
